### ISSUE TITLE
Documentation points to iteration-zero for adding tekton tasks is missing directory

### ISSUE THREAD

**Issue by airazabal** [ibm-garage-cloud/template-node-typescript#8]
In the README.md file there are instructions to add the tekton tasks required for the typescript nodejs application. When you clone the iteration zero git, the tekton directory is missing:
irazabal@us.ibm.com@alexs-MacBook-Pro Documents % git clone https://github.com/ibm-garage-cloud/ibm-garage-iteration-zero.git
Cloning into 'ibm-garage-iteration-zero'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 2408 (delta 11), reused 12 (delta 4), pack-reused 2387
Receiving objects: 100% (2408/2408), 2.04 MiB | 10.95 MiB/s, done.
Resolving deltas: 100% (1386/1386), done.
irazabal@us.ibm.com@alexs-MacBook-Pro Documents % cd ibm-garage-iteration-zero
irazabal@us.ibm.com@alexs-MacBook-Pro ibm-garage-iteration-zero % ls -l
total 40
-rwxr-xr-x  1 irazabal@us.ibm.com  staff  1059 Nov 13 10:59 LICENSE
-rw-r--r--  1 irazabal@us.ibm.com  staff  4595 Nov 13 10:59 README.md
-rw-r--r--  1 irazabal@us.ibm.com  staff   228 Nov 13 10:59 credentials.template
drwxr-xr-x  5 irazabal@us.ibm.com  staff   160 Nov 13 10:59 docs
-rwxr-xr-x  1 irazabal@us.ibm.com  staff  2737 Nov 13 10:59 launch.sh
drwxr-xr-x  8 irazabal@us.ibm.com  staff   256 Nov 13 10:59 terraform

**Comment by mjperrins** [comment]
The Tekton tasks having been moved outside iZero into its own repository, I will fix the README issue to make that clear
